package me.adrian.skymining.commands;

import me.adrian.skymining.SkyMining;
import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Entity;
import org.bukkit.entity.EntityType;
import org.bukkit.entity.Player;
import org.bukkit.entity.Villager;
import org.bukkit.inventory.MerchantRecipe;
import org.jetbrains.annotations.NotNull;

import java.security.Permission;

public class villagerrestore implements CommandExecutor {



    @Override
    public boolean onCommand(@NotNull CommandSender commandSender, @NotNull Command command, @NotNull String s, @NotNull String[] strings) {
        if (commandSender instanceof Player) {
            Player player = ((Player) commandSender).getPlayer();

            if (player.hasPermission("skyminer.restorevillager")) {

                //Oak Tools
                player.performCommand("summon villager 2 95 42 {HasVisualFire:0b,Invulnerable:1b,CustomNameVisible:1b,NoAI:1b,CanPickUpLoot:0b,Rotation:[180F,0F],CustomName:'{\"text\":\"Oak Tools\",\"color\":\"#573B3B\",\"bold\":true}',HandItems:[{id:\"minecraft:wooden_axe\",Count:1b},{}],VillagerData:{level:99,profession:\"minecraft:toolsmith\",type:\"minecraft:plains\"},Offers:{Recipes:[{rewardExp:0b,buy:{id:\"minecraft:oak_log\",Count:16b},sell:{id:\"minecraft:wooden_axe\",Count:1b,tag:{Unbreakable:1b}}},{rewardExp:0b,buy:{id:\"minecraft:oak_log\",Count:32b},buyB:{id:\"minecraft:wooden_axe\",Count:1b,tag:{Unbreakable:1b}},sell:{id:\"minecraft:wooden_axe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:1s}]}}},{rewardExp:0b,buy:{id:\"minecraft:oak_log\",Count:2b,tag:{display:{Name:'{\"text\":\"Compressed Oak Log\",\"color\":\"white\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:wooden_axe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:1s}]}},sell:{id:\"minecraft:wooden_axe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:2s}]}}},{rewardExp:0b,buy:{id:\"minecraft:oak_log\",Count:4b,tag:{display:{Name:'{\"text\":\"Compressed Oak Log\",\"color\":\"white\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:wooden_axe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:2s}]}},sell:{id:\"minecraft:wooden_axe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:3s}]}}},{rewardExp:0b,buy:{id:\"minecraft:oak_log\",Count:8b,tag:{display:{Name:'{\"text\":\"Compressed Oak Log\",\"color\":\"white\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:wooden_axe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:3s}]}},sell:{id:\"minecraft:wooden_axe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:4s}]}}}]}}");


                //Oak Compresssor
                player.performCommand("summon villager 0 95 43 {HasVisualFire:0b,Invulnerable:1b,CustomNameVisible:1b,NoAI:1b,CanPickUpLoot:0b,Rotation:[180F,0F],CustomName:'{\"text\":\"Oak Compressor\",\"color\":\"#573B3B\",\"bold\":true}',ArmorItems:[{},{},{},{id:\"minecraft:oak_log\",Count:1b,tag:{Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}],VillagerData:{level:99,profession:\"minecraft:toolsmith\",type:\"minecraft:plains\"},Offers:{Recipes:[{rewardExp:0b,buy:{id:\"minecraft:oak_log\",Count:32b},sell:{id:\"minecraft:oak_log\",Count:1b,tag:{display:{Name:'{\"text\":\"Compressed Oak Log\",\"color\":\"white\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}},{rewardExp:0b,buy:{id:\"minecraft:oak_log\",Count:64b},sell:{id:\"minecraft:oak_log\",Count:2b,tag:{display:{Name:'{\"text\":\"Compressed Oak Log\",\"color\":\"white\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}},{rewardExp:0b,buy:{id:\"minecraft:oak_log\",Count:64b},buyB:{id:\"minecraft:oak_log\",Count:64b},sell:{id:\"minecraft:oak_log\",Count:4b,tag:{display:{Name:'{\"text\":\"Compressed Oak Log\",\"color\":\"white\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}}]}}");


                //Oak Armor
                player.performCommand("summon villager -1.5 95 42.5 {HasVisualFire:0b,Invulnerable:1b,CustomNameVisible:1b,NoAI:1b,CanPickUpLoot:0b,Rotation:[180F,0F],CustomName:'{\"text\":\"Oak Armor\",\"color\":\"#573B3B\",\"bold\":true}',HandItems:[{id:\"minecraft:leather_chestplate\",Count:1b,tag:{display:{color:7885376}}},{}],VillagerData:{level:99,profession:\"minecraft:toolsmith\",type:\"minecraft:plains\"},Offers:{Recipes:[{rewardExp:0b,buy:{id:\"minecraft:oak_log\",Count:2b,tag:{display:{Name:'{\"text\":\"Compressed Oak Log\",\"color\":\"white\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},sell:{id:\"minecraft:leather_helmet\",Count:1b,tag:{display:{color:7885376},Unbreakable:1b}}},{rewardExp:0b,buy:{id:\"minecraft:oak_log\",Count:4b,tag:{display:{Name:'{\"text\":\"Compressed Oak Log\",\"color\":\"white\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},sell:{id:\"minecraft:leather_chestplate\",Count:1b,tag:{display:{color:7885376},Unbreakable:1b}}},{rewardExp:0b,buy:{id:\"minecraft:oak_log\",Count:4b,tag:{display:{Name:'{\"text\":\"Compressed Oak Log\",\"color\":\"white\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},sell:{id:\"minecraft:leather_leggings\",Count:1b,tag:{display:{color:7885376},Unbreakable:1b}}},{buy:{id:\"minecraft:oak_log\",Count:2b,tag:{display:{Name:'{\"text\":\"Compressed Oak Log\",\"color\":\"white\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},sell:{id:\"minecraft:leather_boots\",Count:1b,tag:{display:{color:7885376},Unbreakable:1b}}}]}}");


                //Birch Tools
                player.performCommand("summon villager -24.5 98 55.5 {HasVisualFire:0b,Invulnerable:1b,CustomNameVisible:1b,NoAI:1b,CanPickUpLoot:0b,Rotation:[180F,0F],CustomName:'{\"text\":\"Birch Tools\",\"color\":\"#FFE799\",\"bold\":true}',HandItems:[{id:\"minecraft:wooden_axe\",Count:1b,tag:{Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},{}],VillagerData:{level:99,profession:\"minecraft:toolsmith\",type:\"minecraft:plains\"},Offers:{Recipes:[{rewardExp:0b,buy:{id:\"minecraft:birch_log\",Count:32b},buyB:{id:\"minecraft:wooden_axe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:4s}]}},sell:{id:\"minecraft:stone_axe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:1s}]}}},{rewardExp:0b,buy:{id:\"minecraft:birch_log\",Count:4b,tag:{display:{Name:'{\"text\":\"Compressed Birch Log\",\"color\":\"#FFE799\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:stone_axe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:1s}]}},sell:{id:\"minecraft:stone_axe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:2s}]}}},{rewardExp:0b,buy:{id:\"minecraft:birch_log\",Count:6b,tag:{display:{Name:'{\"text\":\"Compressed Birch Log\",\"color\":\"#FFE799\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:stone_axe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:2s}]}},sell:{id:\"minecraft:stone_axe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:3s}]}}},{rewardExp:0b,buy:{id:\"minecraft:birch_log\",Count:8b,tag:{display:{Name:'{\"text\":\"Compressed Birch Log\",\"color\":\"#FFE799\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:stone_axe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:3s}]}},sell:{id:\"minecraft:stone_axe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:4s}]}}},{rewardExp:0b,buy:{id:\"minecraft:birch_log\",Count:10b,tag:{display:{Name:'{\"text\":\"Compressed Birch Log\",\"color\":\"#FFE799\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:stone_axe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:4s}]}},sell:{id:\"minecraft:stone_axe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:5s}]}}}]}}");


                //Birch Compressor
                player.performCommand("summon villager -26.5 98 56.5 {HasVisualFire:0b,Invulnerable:1b,CustomNameVisible:1b,NoAI:1b,CanPickUpLoot:0b,Rotation:[180F,0F],CustomName:'{\"text\":\"Birch Compressor\",\"color\":\"#FFE799\",\"bold\":true}',ArmorItems:[{},{},{},{id:\"minecraft:birch_log\",Count:1b,tag:{Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}],VillagerData:{level:99,profession:\"minecraft:toolsmith\",type:\"minecraft:plains\"},Offers:{Recipes:[{rewardExp:0b,buy:{id:\"minecraft:birch_log\",Count:32b},sell:{id:\"minecraft:birch_log\",Count:1b,tag:{display:{Name:'{\"text\":\"Compressed Birch Log\",\"color\":\"#FFE799\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}},{rewardExp:0b,buy:{id:\"minecraft:birch_log\",Count:64b},sell:{id:\"minecraft:birch_log\",Count:2b,tag:{display:{Name:'{\"text\":\"Compressed Birch Log\",\"color\":\"#FFE799\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}},{rewardExp:0b,buy:{id:\"minecraft:birch_log\",Count:64b},buyB:{id:\"minecraft:birch_log\",Count:64b},sell:{id:\"minecraft:birch_log\",Count:4b,tag:{display:{Name:'{\"text\":\"Compressed Birch Log\",\"color\":\"#FFE799\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}}]}}");


                //Birch Armor
                player.performCommand("summon villager -28.5 98 55.5 {HasVisualFire:0b,Invulnerable:1b,CustomNameVisible:1b,NoAI:1b,CanPickUpLoot:0b,Rotation:[180F,0F],CustomName:'{\"text\":\"Birch Armor\",\"color\":\"#FFE799\",\"bold\":true}',HandItems:[{id:\"minecraft:leather_chestplate\",Count:1b,tag:{display:{color:16770969},Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},{}],VillagerData:{level:99,profession:\"minecraft:toolsmith\",type:\"minecraft:plains\"},Offers:{Recipes:[{rewardExp:0b,buy:{id:\"minecraft:birch_log\",Count:4b,tag:{display:{Name:'{\"text\":\"Compressed Birch Log\",\"color\":\"#FFE799\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:leather_helmet\",Count:1b,tag:{display:{color:7885376},Unbreakable:1b}},sell:{id:\"minecraft:leather_helmet\",Count:1b,tag:{display:{color:16770969},Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:2s}]}}},{rewardExp:0b,buy:{id:\"minecraft:birch_log\",Count:8b,tag:{display:{Name:'{\"text\":\"Compressed Birch Log\",\"color\":\"#FFE799\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:leather_chestplate\",Count:1b,tag:{display:{color:7885376},Unbreakable:1b}},sell:{id:\"minecraft:leather_chestplate\",Count:1b,tag:{display:{color:16770969},Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:2s}]}}},{rewardExp:0b,buy:{id:\"minecraft:birch_log\",Count:8b,tag:{display:{Name:'{\"text\":\"Compressed Birch Log\",\"color\":\"#FFE799\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:leather_leggings\",Count:1b,tag:{display:{color:7885376},Unbreakable:1b}},sell:{id:\"minecraft:leather_leggings\",Count:1b,tag:{display:{color:16770969},Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:2s}]}}},{buy:{id:\"minecraft:birch_log\",Count:4b,tag:{display:{Name:'{\"text\":\"Compressed Birch Log\",\"color\":\"#FFE799\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:leather_boots\",Count:1b,tag:{display:{color:7885376},Unbreakable:1b}},sell:{id:\"minecraft:leather_boots\",Count:1b,tag:{display:{color:16770969},Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:2s}]}}}]}}");


                //Bohrer
                player.performCommand("summon villager -23.5 104 79.5 {Invulnerable:1b,CustomNameVisible:1b,NoAI:1b,Rotation:[180F,0F],CustomName:'{\"text\":\"Bohrer Trader\",\"color\":\"#4F4F4F\",\"bold\":true}',HandItems:[{id:\"minecraft:wooden_pickaxe\",Count:1b},{}],VillagerData:{level:99,profession:\"minecraft:toolsmith\",type:\"minecraft:taiga\"},Offers:{Recipes:[{rewardExp:0b,maxUses:9999999,uses:0,xp:0,priceMultiplier:0f,specialPrice:0,demand:0,buy:{id:\"minecraft:oak_log\",Count:16b,tag:{display:{Name:'{\"text\":\"Compressed Oak Log\",\"color\":\"white\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:birch_log\",Count:16b,tag:{display:{Name:'{\"text\":\"Compressed Birch Log\",\"color\":\"#FFE799\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},sell:{id:\"minecraft:wooden_pickaxe\",Count:1b,tag:{Unbreakable:0b,Damage:43}}}]}}");


                //Stone Tools
                player.performCommand("summon villager -0.5 103 65 {OnGround:1b,NoGravity:1b,CustomNameVisible:1b,NoAI:1b,CustomName:'{\"text\":\"Stone Tools\",\"color\":\"#4F4F4F\",\"bold\":true}',HandItems:[{id:\"minecraft:wooden_pickaxe\",Count:1b,tag:{Enchantments:[{}]}},{}],VillagerData:{level:99,profession:\"minecraft:toolsmith\",type:\"minecraft:taiga\"},Offers:{Recipes:[{rewardExp:0b,maxUses:9999,uses:0,xp:0,demand:0,buy:{id:\"minecraft:cobblestone\",Count:16b},sell:{id:\"minecraft:wooden_pickaxe\",Count:1b,tag:{Unbreakable:1b}}},{rewardExp:0b,maxUses:9999,uses:0,xp:0,demand:0,buy:{id:\"minecraft:cobblestone\",Count:32b},buyB:{id:\"minecraft:wooden_pickaxe\",Count:1b,tag:{Unbreakable:1b}},sell:{id:\"minecraft:wooden_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:1s}]}}},{rewardExp:0b,maxUses:9999,uses:0,xp:0,demand:0,buy:{id:\"minecraft:stone\",Count:4b,tag:{display:{Name:'{\"text\":\"Compressed Stone\",\"color\":\"#4F4F4F\",\"bold\":true}'},CustomModelData:1,Enchantments:[{}]}},buyB:{id:\"minecraft:wooden_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:1s}]}},sell:{id:\"minecraft:wooden_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:2s}]}}},{rewardExp:0b,maxUses:9999,uses:0,xp:0,demand:0,buy:{id:\"minecraft:stone\",Count:6b,tag:{display:{Name:'{\"text\":\"Compressed Stone\",\"color\":\"#4F4F4F\",\"bold\":true}'},CustomModelData:1,Enchantments:[{}]}},buyB:{id:\"minecraft:wooden_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:2s}]}},sell:{id:\"minecraft:wooden_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:3s}]}}},{rewardExp:0b,maxUses:9999,uses:0,xp:0,demand:0,buy:{id:\"minecraft:stone\",Count:8b,tag:{display:{Name:'{\"text\":\"Compressed Stone\",\"color\":\"#4F4F4F\",\"bold\":true}'},CustomModelData:1,Enchantments:[{}]}},buyB:{id:\"minecraft:wooden_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:3s}]}},sell:{id:\"minecraft:wooden_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:4s}]}}}]}}");


                //Stone Compressor
                player.performCommand("summon villager 1.5 103 64.5 {HasVisualFire:0b,Invulnerable:1b,CustomNameVisible:1b,NoAI:1b,CanPickUpLoot:0b,CustomName:'{\"text\":\"Stone Compressor\",\"color\":\"#4F4F4F\",\"bold\":true}',ArmorItems:[{},{},{},{id:\"minecraft:stone\",Count:1b,tag:{Enchantments:[{}]}}],VillagerData:{level:99,profession:\"minecraft:toolsmith\",type:\"minecraft:taiga\"},Offers:{Recipes:[{rewardExp:0b,buy:{id:\"minecraft:cobblestone\",Count:32b},sell:{id:\"minecraft:stone\",Count:1b,tag:{display:{Name:'{\"text\":\"Compressed Stone\",\"color\":\"#4F4F4F\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}},{rewardExp:0b,buy:{id:\"minecraft:cobblestone\",Count:64b},sell:{id:\"minecraft:stone\",Count:2b,tag:{display:{Name:'{\"text\":\"Compressed Stone\",\"color\":\"#4F4F4F\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}},{rewardExp:0b,buy:{id:\"minecraft:cobblestone\",Count:64b},buyB:{id:\"minecraft:cobblestone\",Count:64b},sell:{id:\"minecraft:stone\",Count:4b,tag:{display:{Name:'{\"text\":\"Compressed Stone\",\"color\":\"#4F4F4F\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}}]}}");


                //Stone Armour
                player.performCommand("summon villager 3.5 103 65.5 {OnGround:1b,NoGravity:1b,CustomNameVisible:1b,NoAI:1b,CustomName:'{\"text\":\"Stone Armour\",\"color\":\"#4F4F4F\",\"bold\":true}',HandItems:[{id:\"minecraft:leather_chestplate\",Count:1b,tag:{display:{color:5197647},Enchantments:[{id:\"minecraft:protection\",lvl:3s}]}},{}],VillagerData:{level:99,profession:\"minecraft:toolsmith\",type:\"minecraft:taiga\"},Offers:{Recipes:[{rewardExp:0b,maxUses:9999,uses:0,xp:0,demand:0,buy:{id:\"minecraft:stone\",Count:4b,tag:{display:{Name:'{\"text\":\"Compressed Stone\",\"color\":\"#4F4F4F\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:leather_helmet\",Count:1b,tag:{display:{color:16770969},Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:2s}]}},sell:{id:\"minecraft:leather_helmet\",Count:1b,tag:{display:{color:5197647},Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:3s}]}}},{rewardExp:0b,maxUses:9999,uses:0,xp:0,demand:0,buy:{id:\"minecraft:stone\",Count:8b,tag:{display:{Name:'{\"text\":\"Compressed Stone\",\"color\":\"#4F4F4F\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:leather_chestplate\",Count:1b,tag:{display:{color:16770969},Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:2s}]}},sell:{id:\"minecraft:leather_chestplate\",Count:1b,tag:{display:{color:5197647},Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:3s}]}}},{rewardExp:0b,maxUses:9999,uses:0,xp:0,demand:0,buy:{id:\"minecraft:stone\",Count:8b,tag:{display:{Name:'{\"text\":\"Compressed Stone\",\"color\":\"#4F4F4F\",\"bold\":true}'},CustomModelData:1,Enchantments:[{}]}},buyB:{id:\"minecraft:leather_leggings\",Count:1b,tag:{display:{color:16770969},Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:2s}]}},sell:{id:\"minecraft:leather_leggings\",Count:1b,tag:{display:{color:5197647},Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:3s}]}}},{rewardExp:0b,maxUses:9999,uses:0,xp:0,demand:0,buy:{id:\"minecraft:stone\",Count:8b,tag:{display:{Name:'{\"text\":\"Compressed Stone\",\"color\":\"#4F4F4F\",\"bold\":true}'},CustomModelData:1,Enchantments:[{}]}},buyB:{id:\"minecraft:leather_boots\",Count:1b,tag:{display:{color:16770969},Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:2s}]}},sell:{id:\"minecraft:leather_boots\",Count:1b,tag:{display:{color:5197647},Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:3s}]}}}]}}");


                //Gold Bohrer
                player.performCommand("summon villager 45.5 124 -33.5 {CustomNameVisible:1b,NoAI:1b,CustomName:'{\"text\":\"Goldbohrer\",\"color\":\"#F4C22F\",\"bold\":true}',HandItems:[{id:\"minecraft:iron_pickaxe\",Count:1b},{}],VillagerData:{level:99,profession:\"minecraft:cartographer\",type:\"minecraft:taiga\"},Offers:{Recipes:[{rewardExp:0b,buy:{id:\"minecraft:raw_iron_block\",Count:16b,tag:{display:{Name:'{\"text\":\"Compressed Iron\",\"color\":\"#806857\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:coal_block\",Count:16b,tag:{display:{Name:'{\"text\":\"Compressed Coal\",\"color\":\"#191919\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},sell:{id:\"minecraft:iron_pickaxe\",Count:1b,tag:{display:{Name:'{\"text\":\"Goldbohrer\",\"color\":\"#F4C22F\",\"bold\":true}'},Damage:218,CustomModelData:1}}}]}}");

                //Coal Tools
                player.performCommand("summon villager 21 110 37 {OnGround:1b,NoGravity:1b,CustomNameVisible:1b,NoAI:1b,Rotation:[270F,0F],CustomName:'{\"text\":\"Coal Tools\",\"color\":\"#191919\",\"bold\":true}',HandItems:[{id:\"minecraft:stone_pickaxe\",Count:1b},{}],VillagerData:{level:99,profession:\"minecraft:toolsmith\",type:\"minecraft:taiga\"},Offers:{Recipes:[{rewardExp:0b,maxUses:9999,uses:0,xp:0,demand:0,buy:{id:\"minecraft:coal\",Count:32b},buyB:{id:\"minecraft:wooden_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:4s}]}},sell:{id:\"minecraft:stone_pickaxe\",Count:1b,tag:{Unbreakable:1b}}},{rewardExp:0b,maxUses:9999,uses:0,xp:0,demand:0,buy:{id:\"minecraft:coal_block\",Count:4b,tag:{display:{Name:'{\"text\":\"Compressed Coal\",\"color\":\"#191919\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:stone_pickaxe\",Count:1b,tag:{Unbreakable:1b}},sell:{id:\"minecraft:stone_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:1s}]}}},{rewardExp:0b,maxUses:9999,uses:0,xp:0,demand:0,buy:{id:\"minecraft:coal_block\",Count:6b,tag:{display:{Name:'{\"text\":\"Compressed Coal\",\"color\":\"#191919\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:stone_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:1s}]}},sell:{id:\"minecraft:stone_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:2s}]}}},{rewardExp:0b,maxUses:9999,uses:0,xp:0,demand:0,buy:{id:\"minecraft:coal_block\",Count:8b,tag:{display:{Name:'{\"text\":\"Compressed Coal\",\"color\":\"#191919\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:stone_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:2s}]}},sell:{id:\"minecraft:stone_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:3s}]}}},{rewardExp:0b,maxUses:9999,uses:0,xp:0,demand:0,buy:{id:\"minecraft:coal_block\",Count:12b,tag:{display:{Name:'{\"text\":\"Compressed Coal\",\"color\":\"#191919\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:stone_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:3s}]}},sell:{id:\"minecraft:stone_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:4s},{id:\"minecraft:fortune\",lvl:1s}]}}}]}}");


                //Coal Compressor
                player.performCommand("summon villager 20.5 110 35.5 {HasVisualFire:0b,Invulnerable:1b,CustomNameVisible:1b,NoAI:1b,CanPickUpLoot:0b,Rotation:[270F,0F],CustomName:'{\"text\":\"Coal Compressor\",\"color\":\"#191919\",\"bold\":true}',ArmorItems:[{},{},{},{id:\"minecraft:coal_block\",Count:1b,tag:{Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}],VillagerData:{level:99,profession:\"minecraft:toolsmith\",type:\"minecraft:taiga\"},Offers:{Recipes:[{rewardExp:0b,buy:{id:\"minecraft:coal\",Count:32b},sell:{id:\"minecraft:coal_block\",Count:1b,tag:{display:{Name:'{\"text\":\"Compressed Coal\",\"color\":\"#191919\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}},{rewardExp:0b,buy:{id:\"minecraft:coal\",Count:64b},sell:{id:\"minecraft:coal_block\",Count:2b,tag:{display:{Name:'{\"text\":\"Compressed Coal\",\"color\":\"#191919\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}},{rewardExp:0b,buy:{id:\"minecraft:coal\",Count:64b},buyB:{id:\"minecraft:coal\",Count:64b},sell:{id:\"minecraft:coal_block\",Count:4b,tag:{display:{Name:'{\"text\":\"Compressed Coal\",\"color\":\"#191919\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}}]}}");


                //Coal Armor
                player.performCommand("summon villager 21 110 33 {HasVisualFire:0b,Invulnerable:1b,CustomNameVisible:1b,NoAI:1b,CanPickUpLoot:0b,Rotation:[270F,0F],CustomName:'{\"text\":\"Coal Armor\",\"color\":\"#191919\",\"bold\":true}',HandItems:[{id:\"minecraft:leather_chestplate\",Count:1b,tag:{display:{color:5197647},Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},{}],VillagerData:{level:99,profession:\"minecraft:toolsmith\",type:\"minecraft:taiga\"},Offers:{Recipes:[{rewardExp:0b,buy:{id:\"minecraft:coal_block\",Count:4b,tag:{display:{Name:'{\"text\":\"Compressed Coal\",\"color\":\"#191919\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:leather_helmet\",Count:1b,tag:{display:{color:5197647},Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:3s}]}},sell:{id:\"minecraft:leather_helmet\",Count:1b,tag:{display:{color:1908001},Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:4s}]}}},{rewardExp:0b,buy:{id:\"minecraft:coal_block\",Count:8b,tag:{display:{Name:'{\"text\":\"Compressed Coal\",\"color\":\"#191919\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:leather_chestplate\",Count:1b,tag:{display:{color:5197647},Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:3s}]}},sell:{id:\"minecraft:leather_chestplate\",Count:1b,tag:{display:{color:1908001},Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:4s}]}}},{rewardExp:0b,buy:{id:\"minecraft:coal_block\",Count:8b,tag:{display:{Name:'{\"text\":\"Compressed Coal\",\"color\":\"#191919\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:leather_leggings\",Count:1b,tag:{display:{color:5197647},Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:3s}]}},sell:{id:\"minecraft:leather_leggings\",Count:1b,tag:{display:{color:1908001},Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:4s}]}}},{buy:{id:\"minecraft:coal_block\",Count:4b,tag:{display:{Name:'{\"text\":\"Compressed Coal\",\"color\":\"#191919\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:leather_boots\",Count:1b,tag:{display:{color:5197647},Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:3s}]}},sell:{id:\"minecraft:leather_boots\",Count:1b,tag:{display:{color:1908001},Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:4s}]}}}]}}");


                //Iron Tools
                player.performCommand("summon villager 42.5 116 3.5 {Invulnerable:1b,CustomNameVisible:1b,NoAI:1b,Rotation:[90F,0F],CustomName:'{\"text\":\"Iron Tools\",\"color\":\"#806857\",\"bold\":true}',HandItems:[{id:\"minecraft:stone_pickaxe\",Count:1b,tag:{Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},{}],VillagerData:{level:99,type:\"minecraft:taiga\"},Offers:{Recipes:[{rewardExp:0b,buy:{id:\"minecraft:raw_iron\",Count:32b},buyB:{id:\"minecraft:stone_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:4s},{id:\"minecraft:fortune\",lvl:1s}]}},sell:{id:\"minecraft:stone_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:5s},{id:\"minecraft:fortune\",lvl:1s}]}}},{buy:{id:\"minecraft:raw_iron_block\",Count:4b,tag:{display:{Name:'{\"text\":\"Compressed Iron\",\"color\":\"#806857\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:stone_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:5s},{id:\"minecraft:fortune\",lvl:1s}]}},sell:{id:\"minecraft:stone_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:5s},{id:\"minecraft:fortune\",lvl:2s}]}}},{buy:{id:\"minecraft:raw_iron_block\",Count:6b,tag:{display:{Name:'{\"text\":\"Compressed Iron\",\"color\":\"#806857\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:stone_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:5s},{id:\"minecraft:fortune\",lvl:2s}]}},sell:{id:\"minecraft:stone_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:5s},{id:\"minecraft:fortune\",lvl:3s}]}}},{buy:{id:\"minecraft:raw_iron_block\",Count:8b,tag:{display:{Name:'{\"text\":\"Compressed Iron\",\"color\":\"#806857\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:stone_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:5s},{id:\"minecraft:fortune\",lvl:3s}]}},sell:{id:\"minecraft:stone_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:5s},{id:\"minecraft:fortune\",lvl:4s}]}}},{buy:{id:\"minecraft:raw_iron_block\",Count:10b,tag:{display:{Name:'{\"text\":\"Compressed Iron\",\"color\":\"#806857\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:stone_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:5s},{id:\"minecraft:fortune\",lvl:4s}]}},sell:{id:\"minecraft:stone_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:5s},{id:\"minecraft:fortune\",lvl:5s}]}}}]}}");


                //Iron Compressor
                player.performCommand("summon villager 43 116 5 {OnGround:1b,NoGravity:1b,CustomNameVisible:1b,NoAI:1b,Rotation:[90F,0F],CustomName:'{\"text\":\"Iron Compressor\",\"color\":\"#806857\",\"bold\":true}',ArmorItems:[{},{},{},{id:\"minecraft:raw_iron_block\",Count:1b,tag:{Enchantments:[{}]}}],VillagerData:{level:99,profession:\"minecraft:toolsmith\",type:\"minecraft:taiga\"},Offers:{Recipes:[{rewardExp:0b,maxUses:9999,uses:0,xp:0,demand:0,buy:{id:\"minecraft:raw_iron\",Count:32b},sell:{id:\"minecraft:raw_iron_block\",Count:1b,tag:{display:{Name:'{\"text\":\"Compressed Iron\",\"color\":\"#806857\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}},{rewardExp:0b,maxUses:9999,uses:0,xp:0,demand:0,buy:{id:\"minecraft:raw_iron\",Count:64b},sell:{id:\"minecraft:raw_iron_block\",Count:2b,tag:{display:{Name:'{\"text\":\"Compressed Iron\",\"color\":\"#806857\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}},{rewardExp:0b,maxUses:9999,uses:0,xp:0,demand:0,buy:{id:\"minecraft:raw_iron\",Count:64b},buyB:{id:\"minecraft:raw_iron\",Count:64b},sell:{id:\"minecraft:raw_iron_block\",Count:4b,tag:{display:{Name:'{\"text\":\"Compressed Iron\",\"color\":\"#806857\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}}]}}");


                //Iron Armor
                player.performCommand("summon villager 42 116 7 {HasVisualFire:0b,Invulnerable:1b,CustomNameVisible:1b,NoAI:1b,CanPickUpLoot:0b,Rotation:[90F,0F],CustomName:'{\"text\":\"Iron Armor\",\"color\":\"#806857\",\"bold\":true}',HandItems:[{id:\"minecraft:chainmail_chestplate\",Count:1b,tag:{Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},{}],VillagerData:{level:99,profession:\"minecraft:toolsmith\",type:\"minecraft:taiga\"},Offers:{Recipes:[{rewardExp:0b,buy:{id:\"minecraft:raw_iron_block\",Count:4b,tag:{display:{Name:'{\"text\":\"Compressed Iron\",\"color\":\"#806857\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:leather_helmet\",Count:1b,tag:{display:{color:1908001},Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:4s}]}},sell:{id:\"minecraft:chainmail_helmet\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:1s}]}}},{rewardExp:0b,buy:{id:\"minecraft:raw_iron_block\",Count:8b,tag:{display:{Name:'{\"text\":\"Compressed Iron\",\"color\":\"#806857\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:leather_chestplate\",Count:1b,tag:{display:{color:1908001},Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:4s}]}},sell:{id:\"minecraft:chainmail_chestplate\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:1s}]}}},{rewardExp:0b,buy:{id:\"minecraft:raw_iron_block\",Count:8b,tag:{display:{Name:'{\"text\":\"Compressed Iron\",\"color\":\"#806857\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:leather_leggings\",Count:1b,tag:{display:{color:1908001},Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:4s}]}},sell:{id:\"minecraft:chainmail_leggings\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:1s}]}}},{buy:{id:\"minecraft:raw_iron_block\",Count:4b,tag:{display:{Name:'{\"text\":\"Compressed Iron\",\"color\":\"#806857\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:leather_boots\",Count:1b,tag:{display:{color:1908001},Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:4s}]}},sell:{id:\"minecraft:chainmail_boots\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:1s}]}}}]}}");


                //Gold Tools
                player.performCommand("summon villager 74.5 123 -17.5 {Invulnerable:1b,CustomNameVisible:1b,NoAI:1b,Rotation:[90F,0F],CustomName:'{\"text\":\"Gold Tools\",\"color\":\"#F4C230\",\"bold\":true}',HandItems:[{id:\"minecraft:iron_pickaxe\",Count:1b},{}],VillagerData:{level:99,type:\"minecraft:taiga\"},Offers:{Recipes:[{rewardExp:0b,buy:{id:\"minecraft:raw_gold\",Count:32b},buyB:{id:\"minecraft:stone_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:5s},{id:\"minecraft:fortune\",lvl:5s}]}},sell:{id:\"minecraft:iron_pickaxe\",Count:1b,tag:{Unbreakable:1b}}},{buy:{id:\"minecraft:raw_gold_block\",Count:6b,tag:{display:{Name:'{\"text\":\"Compressed Gold\",\"color\":\"#F4C230\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:iron_pickaxe\",Count:1b,tag:{Unbreakable:1b}},sell:{id:\"minecraft:iron_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:1s},{id:\"minecraft:fortune\",lvl:1s}]}}},{buy:{id:\"minecraft:raw_gold_block\",Count:8b,tag:{display:{Name:'{\"text\":\"Compressed Gold\",\"color\":\"#F4C230\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:iron_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:1s},{id:\"minecraft:fortune\",lvl:1s}]}},sell:{id:\"minecraft:iron_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:2s},{id:\"minecraft:fortune\",lvl:2s}]}}},{buy:{id:\"minecraft:raw_gold_block\",Count:10b,tag:{display:{Name:'{\"text\":\"Compressed Gold\",\"color\":\"#F4C230\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:iron_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:2s},{id:\"minecraft:fortune\",lvl:2s}]}},sell:{id:\"minecraft:iron_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:3s},{id:\"minecraft:fortune\",lvl:3s}]}}},{buy:{id:\"minecraft:raw_gold_block\",Count:12b,tag:{display:{Name:'{\"text\":\"Compressed Gold\",\"color\":\"#F4C230\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:iron_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:3s},{id:\"minecraft:fortune\",lvl:3s}]}},sell:{id:\"minecraft:iron_pickaxe\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:efficiency\",lvl:4s},{id:\"minecraft:fortune\",lvl:4s}]}}}]}}");


                //Gold Compressor
                player.performCommand("summon villager 75.5 123 -15.5 {OnGround:1b,NoGravity:1b,CustomNameVisible:1b,NoAI:1b,Rotation:[90F,0F],CustomName:'{\"text\":\"Gold Compressor\",\"color\":\"#F4C230\",\"bold\":true}',ArmorItems:[{},{},{},{id:\"minecraft:raw_gold_block\",Count:1b,tag:{Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}],VillagerData:{level:99,profession:\"minecraft:toolsmith\",type:\"minecraft:taiga\"},Offers:{Recipes:[{rewardExp:0b,maxUses:9999,uses:0,xp:0,demand:0,buy:{id:\"minecraft:raw_gold\",Count:32b},sell:{id:\"minecraft:raw_gold_block\",Count:1b,tag:{display:{Name:'{\"text\":\"Compressed Gold\",\"color\":\"#F4C230\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}},{rewardExp:0b,maxUses:9999,uses:0,xp:0,demand:0,buy:{id:\"minecraft:raw_gold\",Count:64b},sell:{id:\"minecraft:raw_gold_block\",Count:2b,tag:{display:{Name:'{\"text\":\"Compressed Gold\",\"color\":\"#F4C230\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}},{rewardExp:0b,maxUses:9999,uses:0,xp:0,demand:0,buy:{id:\"minecraft:raw_gold\",Count:64b},buyB:{id:\"minecraft:raw_gold\",Count:64b},sell:{id:\"minecraft:raw_gold_block\",Count:4b,tag:{display:{Name:'{\"text\":\"Compressed Gold\",\"color\":\"#F4C230\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}}]}}");


                //Gold Armor
                player.performCommand("summon villager 74 123 -13.5 {HasVisualFire:0b,Invulnerable:1b,CustomNameVisible:1b,NoAI:1b,CanPickUpLoot:0b,Rotation:[90F,0F],CustomName:'{\"text\":\"Gold Armor\",\"color\":\"#F4C230\",\"bold\":true}',HandItems:[{id:\"minecraft:chainmail_chestplate\",Count:1b,tag:{Enchantments:[{}]}},{}],VillagerData:{level:99,profession:\"minecraft:toolsmith\",type:\"minecraft:taiga\"},Offers:{Recipes:[{rewardExp:0b,buy:{id:\"minecraft:raw_gold_block\",Count:4b,tag:{display:{Name:'{\"text\":\"Compressed Gold\",\"color\":\"#F4C230\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:chainmail_helmet\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:1s}]}},sell:{id:\"minecraft:chainmail_helmet\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:3s}]}}},{rewardExp:0b,buy:{id:\"minecraft:raw_gold_block\",Count:8b,tag:{display:{Name:'{\"text\":\"Compressed Gold\",\"color\":\"#F4C230\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:chainmail_chestplate\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:1s}]}},sell:{id:\"minecraft:chainmail_chestplate\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:3s}]}}},{rewardExp:0b,buy:{id:\"minecraft:raw_gold_block\",Count:8b,tag:{display:{Name:'{\"text\":\"Compressed Gold\",\"color\":\"#F4C230\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:chainmail_leggings\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:1s}]}},sell:{id:\"minecraft:chainmail_leggings\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:3s}]}}},{buy:{id:\"minecraft:raw_gold_block\",Count:4b,tag:{display:{Name:'{\"text\":\"Compressed Gold\",\"color\":\"#F4C230\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}},buyB:{id:\"minecraft:chainmail_boots\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:1s}]}},sell:{id:\"minecraft:chainmail_boots\",Count:1b,tag:{Unbreakable:1b,Enchantments:[{id:\"minecraft:protection\",lvl:3s}]}}}]}}");


                //Diamond Tools
                //


                //Diamond Compressor
                player.performCommand("summon villager 75.5 129 28.5 {OnGround:1b,NoGravity:1b,CustomNameVisible:1b,NoAI:1b,Rotation:[180F,0F],CustomName:'{\"text\":\"Diamond Compressor\",\"color\":\"#1DC9CF\",\"bold\":true}',ArmorItems:[{},{},{},{id:\"minecraft:diamond_block\",Count:1b,tag:{Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}],VillagerData:{level:99,profession:\"minecraft:toolsmith\",type:\"minecraft:taiga\"},Offers:{Recipes:[{rewardExp:0b,maxUses:9999,uses:0,xp:0,demand:0,buy:{id:\"minecraft:diamond\",Count:32b},sell:{id:\"minecraft:diamond_block\",Count:1b,tag:{display:{Name:'{\"text\":\"Compressed Diamond\",\"color\":\"#1DC9CF\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}},{rewardExp:0b,maxUses:9999,uses:0,xp:0,demand:0,buy:{id:\"minecraft:diamond\",Count:64b},sell:{id:\"minecraft:diamond_block\",Count:2b,tag:{display:{Name:'{\"text\":\"Compressed Diamond\",\"color\":\"#1DC9CF\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}},{rewardExp:0b,maxUses:9999,uses:0,xp:0,demand:0,buy:{id:\"minecraft:diamond\",Count:64b},buyB:{id:\"minecraft:diamond\",Count:64b},sell:{id:\"minecraft:diamond_block\",Count:4b,tag:{display:{Name:'{\"text\":\"Compressed Diamond\",\"color\":\"#1DC9CF\",\"bold\":true}'},CustomModelData:1,Enchantments:[{id:\"minecraft:infinity\",lvl:1s}]}}}]}}");


                //Diamond Armor
                //

                player.sendMessage(ChatColor.GREEN + "Die Villager wurden respawned");

                for (Entity entity : player.getWorld().getEntities()) {
                    if (entity.getType().equals(EntityType.VILLAGER)){
                        Villager villager = (Villager) entity;
                        villager.setSilent(true);
                        for (MerchantRecipe recipe : villager.getRecipes()) {
                            recipe.setMaxUses(10000);
                            recipe.setExperienceReward(false);
                        }
                    }
                }
                player.sendMessage(ChatColor.GREEN + "Die Metadaten der Villager wurden gesetzt!");



            } else {


                    player.sendMessage(ChatColor.RED + "Du hst keine Berechtigungen für diesen Command!");


            }



        }
        else{
            commandSender.sendMessage(ChatColor.RED + "You have to be a player!");
        }

        return false;
    }
}