hight: 0
server: 0
location1:
  x:
  y:
  z:
  yaw:
  pitch:
location2:
  x:
  y:
  z:
  yaw:
  pitch:
location3:
  x:
  y:
  z:
  yaw:
  pitch:
location4:
  x:
  y:
  z:
  yaw:
  pitch:
location5:
  x:
  y:
  z:
  yaw:
  pitch:
location6:
  x:
  y:
  z:
  yaw:
  pitch:
location7:
  x:
  y:
  z:
  yaw:
  pitch:
location8:
  x:
  y:
  z:
  yaw:
  pitch:
airnow:
  x:
  y:
  z:
  yaw:
  pitch:
x5: