name: Smasher
version: '${project.version}'
main: me.adrian.smasher.Smasher
api-version: '1.19'
commands:
  lobby:
    description: Teleport to the lobby
    aliases:
      - l
      - hub
  discord:
    description: Go to our discord
    aliases:
      - dc

