name: SkyMining
version: '1.0'
main: me.adrian.skymining.SkyMining
api-version: '1.19'
commands:
  restoregamerules:
    description: Setzte alle Gamerules wieder auf den Basiswert!
  restorevillager:
    description: Respawn all the villagers.
  lobby:
    description: Go to the lobby
    aliases:
      - l
      - hub

